# Generated by Django 4.2.14 on 2024-07-19 07:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('tags', models.CharField(choices=[('shane', 'Shane'), ('reggie', 'Reggie')], max_length=155)),
                ('image_card', models.ImageField(upload_to='cats_images/')),
                ('image_cover', models.ImageField(upload_to='cats_images/')),
                ('video', models.FileField(upload_to='cats_videos/')),
            ],
        ),
    ]
