# Generated by Django 4.2.14 on 2024-07-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cat',
            name='tags',
            field=models.CharField(choices=[('shane', 'Shane'), ('reggie', 'Reggie'), ('shane and reggie', 'Shane and Reggie')], max_length=155),
        ),
    ]
